### ISSUE TITLE
Shortcut J activates in composition field

### ISSUE THREAD

**Issue by PN3UMA** [flathub/social.whalebird.WhalebirdDesktop#13]
## Description
I cannot type the letter 'j' in the composition field because it activates the assigned shortcut 'Select the next post.'

## How To Reproduce
1. Click into 'What's on your mind?' field.
2. Type the letter 'j.'
3. Instead of typing 'j,' it activates the assigned shortcut "Select the next post."

## My Environment
 - OS: [e.g. Debian 11 Bullseye]
 - Whalebird Version: [5.0.0 (flatpak says 4.7.4?)]
 - Instance: [e.g. fosstodon.org]
---
labels: bug
---

**Comment by Lunarequest** [comment]
this is a default binding in whalebird not an issue
