### ISSUE TITLE
Recent updates are not released?

### ISSUE THREAD

**Issue by h3poteto** [flathub/social.whalebird.WhalebirdDesktop#3]
https://flathub.org/apps/details/social.whalebird.WhalebirdDesktop

The name is still "WhaleBird", this spelling mistake has been already fixed in https://github.com/flathub/social.whalebird.WhalebirdDesktop/pull/2 .
And the current version is still 4.4.6. Why are recent updates not released? The current version should be 4.6.1: https://github.com/flathub/social.whalebird.WhalebirdDesktop/blob/e963fecb725e4abcbac0eba912f0e0622f8eba58/social.whalebird.WhalebirdDesktop.yaml#L58

**Comment by Lunarequest** [comment]
Sorry I've been working on stuff for uni. I haven't got an idea why the auto updates aren't working

**Comment by Lunarequest** [comment]
regarding the spelling issue, it has to be fixed upstream, since we use the flatpak-data from the upstream repo https://github.com/flathub/social.whalebird.WhalebirdDesktop/blob/master/social.whalebird.WhalebirdDesktop.yaml#L49-L50

**Comment by Lunarequest** [comment]
I've updated the package

**Comment by h3poteto** [comment]
When is it released?
https://flathub.org/apps/details/social.whalebird.WhalebirdDesktop is still 4.4.6.

**Comment by Lunarequest** [comment]
It takes abit for it to show up on the page

**Comment by h3poteto** [comment]
Not yet been released. Why?

**Comment by Lunarequest** [comment]
it has been but you need to update the version number upstream in the metainfo.xml file. 
https://github.com/flathub/social.whalebird.WhalebirdDesktop/blob/edb4eef7bd4f5e917dc7c9f3f73bcfc440424fb7/social.whalebird.WhalebirdDesktop.yaml#L58

**Comment by Lunarequest** [comment]
more specifically this line
https://github.com/h3poteto/whalebird-desktop/blob/abfff0afa0b507c617d035dffe67c3d24f07076b/flatpak-data/social.whalebird.WhalebirdDesktop.metainfo.xml#L36

**Comment by h3poteto** [comment]
Oh, thank you. I will update it.

**Comment by Lunarequest** [comment]
note until a new release is cut the metainfo file can't be updated in the flatpak

**Comment by h3poteto** [comment]
I see.
